services:
  dozzle-agent:
    image: amir20/dozzle:v11.1.0@sha256:7c4fb7f8124f5dea15ade881535cc19cc9a03e66639fd28154ff43a93b78944b
    environment:
      - TZ=America/Los_Angeles
    command: agent
    restart: unless-stopped
    volumes:
      - type: bind
        source: /usr/share/zoneinfo
        target: /usr/share/zoneinfo
        read_only: true
        bind:
          create_host_path: false
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/fast/configs/dozzle/dozzle_cert.pem:/dozzle_cert.pem:ro
      - /mnt/fast/configs/dozzle/dozzle_key.pem:/dozzle_key.pem:ro
    ports:
      - 7007:7007
