endpoints:
  - name: docker01
    group: swarm
    url: "icmp://192.168.1.41"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: docker02
    group: swarm
    url: "icmp://192.168.1.42"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: docker03
    group: swarm
    url: "icmp://192.168.1.43"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: swarm vip
    group: swarm
    url: "icmp://192.168.1.45"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: nginx proxy manager
    group: swarm
    url: "http://192.168.1.45:181"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: portainer
    group: swarm
    url: "http://192.168.1.45:9000/api/system/status"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"

  - name: homepage
    group: swarm
    url: "http://192.168.1.45:3000/api/healthcheck"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: dozzle
    group: swarm
    url: "http://192.168.1.41:8888/healthcheck"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: glances docker01
    group: swarm
    url: "http://192.168.1.41:61208/api/4/quicklook"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].mem > 0"

  - name: glances docker02
    group: swarm
    url: "http://192.168.1.42:61208/api/4/quicklook"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].mem > 0"

  - name: glances docker03
    group: swarm
    url: "http://192.168.1.43:61208/api/4/quicklook"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].mem > 0"
