endpoints:
  - name: truenas1
    group: truenas
    url: "icmp://192.168.1.86"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: frigate cameras
    group: truenas
    url: "http://192.168.1.86:5000/api/stats"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].cameras.front_door.camera_fps > 0"
      - "[BODY].cameras.garage.camera_fps > 0"
      - "[BODY].cameras.kitchen.camera_fps > 0"
      - "[BODY].cameras.living_room.camera_fps > 0"
      - "[BODY].cameras.dining_room.camera_fps > 0"
      - "[BODY].cameras.cat_room.camera_fps > 0"
      - "[BODY].cameras.study.camera_fps > 0"
      - "[BODY].cameras.sarah_study.camera_fps > 0"

  - name: prowlarr
    group: truenas
    url: "http://192.168.1.86:9696/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: radarr
    group: truenas
    url: "http://192.168.1.86:7878/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: sonarr
    group: truenas
    url: "http://192.168.1.86:8989/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: jellyfin
    group: truenas
    url: "http://192.168.1.86:8096/health"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: glances
    group: truenas
    url: "http://192.168.1.86:61208/api/4/quicklook"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].mem > 0"

  - name: prometheus
    group: truenas
    url: "http://192.168.1.86:30104/-/healthy"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]
