endpoints:
  - name: truenas1
    group: truenas
    url: "icmp://192.168.1.86"
    interval: 60s
    ui:
      resolve-successful-conditions: true
    conditions: ["[CONNECTED] == true"]

  - name: frigate cameras
    group: truenas
    url: "http://192.168.1.86:5000/api/stats"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].cameras.front_door.camera_fps > 0"
      - "[BODY].cameras.garage.camera_fps > 0"
      - "[BODY].cameras.kitchen.camera_fps > 0"
      - "[BODY].cameras.living_room.camera_fps > 0"
      - "[BODY].cameras.dining_room.camera_fps > 0"
      - "[BODY].cameras.cat_room.camera_fps > 0"
      - "[BODY].cameras.study.camera_fps > 0"
      - "[BODY].cameras.sarah_study.camera_fps > 0"

  - name: prowlarr
    group: truenas
    url: "http://192.168.1.86:9696/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: radarr
    group: truenas
    url: "http://192.168.1.86:7878/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: sonarr
    group: truenas
    url: "http://192.168.1.86:8989/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: bazarr
    group: truenas
    url: "http://192.168.1.86:6767/api/system/ping"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY].status == OK"]

  - name: qbittorrent
    group: truenas
    url: "http://192.168.1.86:8080/"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "[BODY] == pat(*qBittorrent*)"]

  - name: sabnzbd
    group: truenas
    url: "http://192.168.1.86:8081/api?mode=version"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "has([BODY].version) == true"]

  - name: seerr
    group: truenas
    url: "http://192.168.1.86:5055/api/v1/status"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200", "has([BODY].version) == true"]

  - name: profilarr
    group: truenas
    url: "http://192.168.1.86:6868/"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: jellyfin
    group: truenas
    url: "http://192.168.1.86:8096/health"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: glances
    group: truenas
    url: "http://192.168.1.86:61208/api/4/quicklook"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].mem > 0"

  - name: glances processes
    group: truenas
    url: "http://192.168.1.86:61208/api/4/processcount"
    interval: 300s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].total > 20"

  - name: prometheus
    group: truenas
    url: "http://192.168.1.86:30104/-/healthy"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: unpoller
    group: truenas
    url: "http://192.168.1.86:30104/api/v1/query?query=unpoller_device_uptime_seconds%20%3E%200"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == success"
      - "len([BODY].data.result) > 0"

  - name: victorialogs
    group: truenas
    url: "http://192.168.1.86:9428/health"
    interval: 120s
    ui:
      resolve-successful-conditions: true
    conditions: ["[STATUS] == 200"]

  - name: pcie slot fan
    group: truenas
    url: "https://asrock-bmc.mydomain.com/redfish/v1/Chassis/Self/ThermalSubsystem/Fans/20"
    interval: 60s
    headers:
      Authorization: "Basic <base64 of user:password>"
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].Name == FAN4"
      - "[BODY].SpeedPercent.SpeedRPM > 1500"

  - name: asus m.2 card fan
    group: truenas
    url: "https://asrock-bmc.mydomain.com/redfish/v1/Chassis/Self/ThermalSubsystem/Fans/22"
    interval: 60s
    headers:
      Authorization: "Basic <base64 of user:password>"
    ui:
      resolve-successful-conditions: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].Name == FAN6"
      - "[BODY].SpeedPercent.SpeedRPM > 1200"
